# Generated by Django 6.0.1 on 2026-02-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Achievement / certificate image', upload_to='radome/achievements/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AchievementHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(help_text='Blurred background image', upload_to='radome/achievements/highlight/background/')),
                ('overlay_image', models.ImageField(help_text='Center award/logo image', upload_to='radome/achievements/highlight/overlay/')),
            ],
            options={
                'verbose_name': 'Achievement Highlight',
                'verbose_name_plural': 'Achievement Highlight',
            },
        ),
        migrations.CreateModel(
            name='AICoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='our_work/ai_core/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI Core Card',
                'verbose_name_plural': 'AI Core Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Stat value (e.g. 150+, 21, 2)', max_length=20)),
                ('label', models.CharField(help_text='Stat label (e.g. Models Built)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Company Stat',
                'verbose_name_plural': 'Company Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='our_work/industries/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Intro Title')),
                ('image', models.ImageField(help_text='Intro section image', upload_to='home/intro/')),
                ('description', models.TextField(help_text='Intro descriptive text')),
            ],
            options={
                'verbose_name': 'Intro',
                'verbose_name_plural': 'Intro',
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Media gallery image', upload_to='radome/media/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Media Gallery Image',
                'verbose_name_plural': 'Media Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('our_work', 'Our Work'), ('insights', 'Insights'), ('blog', 'Blog'), ('contact', 'Contact')], max_length=50, unique=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='page_banners/images/')),
                ('background_video', models.FileField(blank=True, null=True, upload_to='page_banners/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Portfolio image', upload_to='radome/portfolio/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='our_work/products/banner/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReelVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Reel video file', upload_to='radome/reel/')),
            ],
            options={
                'verbose_name': 'Reel Video',
                'verbose_name_plural': 'Reel Video',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=100)),
                ('position', models.CharField(help_text='Job title / position', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short introduction (optional)', null=True)),
                ('image', models.ImageField(help_text='Team member photo', upload_to='radome/team/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='our_work/usecases/banner/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Value card icon image', upload_to='home/value_icons/')),
                ('text', models.CharField(help_text='Value card description', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Value Card',
                'verbose_name_plural': 'Value Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Right-side image for What We Do section', upload_to='home/what_we_do/')),
            ],
            options={
                'verbose_name': 'What We Do Image',
                'verbose_name_plural': 'What We Do Image',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Icon image', upload_to='home/what_we_do/icons/')),
                ('text', models.CharField(help_text='Description text', max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'What We Do Item',
                'verbose_name_plural': 'What We Do Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IndustryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='our_work/industries/banner/')),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('intro_heading', models.CharField(blank=True, max_length=300)),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='our_work/industries/intro/')),
                ('intro_text', models.TextField(blank=True)),
                ('highlight_text', models.TextField(blank=True, help_text='Black background highlight text')),
                ('product_preview_title', models.CharField(blank=True, help_text='Product preview title', max_length=300)),
                ('product_preview_description', models.TextField(blank=True, help_text='Short product preview text')),
                ('product_preview_image', models.ImageField(blank=True, null=True, upload_to='our_work/industries/product/')),
                ('product_button_text', models.CharField(blank=True, help_text='Button text (e.g. Explore More)', max_length=100)),
                ('use_case_preview_title', models.CharField(blank=True, max_length=255)),
                ('use_case_preview_description', models.TextField(blank=True)),
                ('use_case_button_text', models.CharField(blank=True, max_length=100)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='webapp.industry')),
                ('product', models.ForeignKey(blank=True, help_text='Select product to display', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.product')),
                ('use_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.usecase')),
            ],
        ),
    ]
