# Generated by Django 6.0.1 on 2026-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='title',
            field=models.TextField(blank=True, help_text='Intro Title', null=True),
        ),
    ]
