# Generated by Django 6.0.1 on 2026-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_intro_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tagline',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
