# Generated by Django 6.0.1 on 2026-02-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_product_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModuleIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='our_work/products/module_icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_icons', to='webapp.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
