# Generated by Django 6.0.1 on 2026-02-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_productmoduleicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='UseCaseChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Challenge', max_length=200)),
                ('description', models.TextField()),
                ('use_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='webapp.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='our_work/usecases/features/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='webapp.usecase')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UseCaseSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Solution', max_length=200)),
                ('description', models.TextField()),
                ('use_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='webapp.usecase')),
            ],
        ),
    ]
