# Generated by Django 6.0.1 on 2026-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_usecase_date_usecase_location_usecase_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasechallenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_work/usecases/challenge/'),
        ),
        migrations.AddField(
            model_name='usecasesolution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_work/usecases/solution/'),
        ),
    ]
