# Generated by Django 6.0.1 on 2026-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_usecasechallenge_image_usecasesolution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='date_icon',
            field=models.ImageField(blank=True, null=True, upload_to='our_work/usecases/meta_icons/'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='location_icon',
            field=models.ImageField(blank=True, null=True, upload_to='our_work/usecases/meta_icons/'),
        ),
        migrations.AddField(
            model_name='usecase',
            name='tags_icon',
            field=models.ImageField(blank=True, null=True, upload_to='our_work/usecases/meta_icons/'),
        ),
    ]
