# Generated by Django 6.0.1 on 2026-02-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_blogauthor_remove_blogpost_author_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogsection',
            options={'ordering': ['order', 'id']},
        ),
    ]
