# Generated by Django 6.0.1 on 2026-02-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_blogsection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='section_type',
            field=models.CharField(choices=[('h2', 'Heading (H2 - Main Section)'), ('h3', 'Sub Heading (H3 - Sub Section)'), ('paragraph', 'Paragraph / Bullet List'), ('image', 'Image'), ('conclusion', 'Conclusion')], max_length=20),
        ),
    ]
