# Generated by Django 6.0.1 on 2026-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_blogsection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='is_logo',
            field=models.BooleanField(default=False, help_text='Check this if the image is a company logo'),
        ),
    ]
