# Generated by Django 6.0.1 on 2026-03-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_blogsection_is_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
