# Generated by Django 6.0.1 on 2026-03-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_blogpost_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published_at',
        ),
    ]
